# datasets: 
#   hr_employees: map(include('schema'), any())
#   # customer_faqs: map(include('schema'), any())
#   # transactions: map(include('schema'), any())
#   # employee_faqs: map(include('schema'), any())
# ---
# schema: 
#   description: str()
#   owner: enum("HR", "Finance", "Marketing", "IT")
#   contact: str()
#   datatype: enum("Table", "Document", "Log")
#   location:
#     raw: str()
#     processed: str()
#   classification: enum("PUBLIC", "INTERNAL", "CONFIDENTIAL")
#   contains_pii: bool()
#   pii_fields: list(str())
#   allowed_uses: enum("Fraud Detection", "Public Support", "AI Chatbot", "Internal Knowledge Base")
#   llm_policy:
#     allowed: bool()
#     reason: str()
#   retention:
#     raw_days: int()
#     processed_days: int()

datasets: map(include('dataset_name'))
---
dataset_name: map(include('schema'), any())
schema: 
  description: str()
  owner: enum("HR", "Finance", "Marketing", "IT")
  contact: str()
  datatype: enum("Table", "Document", "Log")
  location:
    raw: str()
    processed: str()
  classification: enum("PUBLIC", "INTERNAL", "CONFIDENTIAL")
  contains_pii: bool()
  pii_fields: list(str())
  allowed_uses: enum("Fraud Detection", "Public Support", "AI Chatbot", "Internal Knowledge Base")
  llm_policy:
    allowed: bool()
    reason: str()
  retention:
    raw_days: int()
    processed_days: int()